#!/usr/bin/env bash

QUICKSHELL_CONFIG_NAME="ii"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
CONFIG_DIR="$XDG_CONFIG_HOME/quickshell/$QUICKSHELL_CONFIG_NAME"
CACHE_DIR="$XDG_CACHE_HOME/quickshell"
STATE_DIR="$XDG_STATE_HOME/quickshell"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$XDG_CONFIG_HOME/illogical-impulse/config.json"
MATERIAL_COLORS_FILE="$STATE_DIR/user/generated/material_colors.scss"

term_alpha=100  # Set to < 100 to make terminals transparent

# Ensure generated dir exists
mkdir -p "$STATE_DIR/user/generated"

# Verify the color file exists and is non-empty before proceeding
if [[ ! -f "$MATERIAL_COLORS_FILE" || ! -s "$MATERIAL_COLORS_FILE" ]]; then
    echo "[applycolor] Error: $MATERIAL_COLORS_FILE not found or empty. Aborting." >&2
    exit 1
fi

# Parse color names and hex values from the SCSS file.
# Format is: $name: #RRGGBB;
# colorlist   = array of "$name" (with the dollar sign)
# colorvalues = array of "#RRGGBB"
declare -a colorlist=()
declare -a colorvalues=()

while IFS= read -r line; do
    # Match lines like:  $primary: #1A2B3C;
    if [[ "$line" =~ ^\$([A-Za-z_][A-Za-z0-9_]*):[[:space:]]*(#[0-9A-Fa-f]{6})\; ]]; then
        colorlist+=("\$${BASH_REMATCH[1]}")
        colorvalues+=("${BASH_REMATCH[2]}")
    fi
done < "$MATERIAL_COLORS_FILE"

if [[ ${#colorlist[@]} -eq 0 ]]; then
    echo "[applycolor] Error: No colors parsed from $MATERIAL_COLORS_FILE." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Terminal theming
# ---------------------------------------------------------------------------
apply_term() {
    local template="$SCRIPT_DIR/terminal/sequences.txt"
    if [[ ! -f "$template" ]]; then
        echo "[applycolor] Terminal template not found at $template. Skipping." >&2
        return 0
    fi

    mkdir -p "$STATE_DIR/user/generated/terminal"
    local dest="$STATE_DIR/user/generated/terminal/sequences.txt"
    cp "$template" "$dest"

    # Apply all color substitutions. The template uses the pattern:
    #   $colorname #  (space before hash is the placeholder marker)
    # We replace that with just the hex digits (no # prefix).
    # Done in a single sed call for speed.
    local sed_expr=""
    for i in "${!colorlist[@]}"; do
        local name="${colorlist[$i]}"      # e.g.  $primary
        local val="${colorvalues[$i]#\#}"  # strip leading #  →  1A2B3C

        # Escape the $ so sed treats it literally
        local escaped_name="${name//\$/\\$}"

        sed_expr+="s/${escaped_name} #/${val}/g;"
    done
    sed_expr+="s/\$alpha/$term_alpha/g"

    sed -i "$sed_expr" "$dest"

    # Push sequences to every open terminal PTY we actually own
    local pushed=0
    for file in /dev/pts/*; do
        [[ "$file" =~ ^/dev/pts/[0-9]+$ ]] || continue
        # Only write to PTYs we have write permission to (avoids Permission denied)
        [[ -w "$file" ]] || continue
        { cat "$dest" > "$file"; } 2>/dev/null & disown $! 2>/dev/null || true
        (( pushed++ )) || true
    done

    if [[ $pushed -eq 0 ]]; then
        echo "[applycolor] No writable PTYs found — terminal colors not pushed." >&2
    fi
}

# ---------------------------------------------------------------------------
# Qt theming (disabled — handled by kde-material-colors)
# ---------------------------------------------------------------------------
apply_qt() {
    sh "$CONFIG_DIR/scripts/kvantum/materialQT.sh"
    python "$CONFIG_DIR/scripts/kvantum/changeAdwColors.py"
}

# ---------------------------------------------------------------------------
# Hyprland border colors — applied live via hyprctl, no restart needed
# Uses:
#   active border   → $primary (with a $primaryContainer glow gradient)
#   inactive border → $surfaceVariant (subtle, low contrast)
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Hyprland border + extra visuals — applied live via hyprctl AND written
# to ~/.config/hypr/material-colors.conf so they survive reboots.
# Add this line to your hyprland.conf:
#   source = ~/.config/hypr/material-colors.conf
# ---------------------------------------------------------------------------

# Helper used by both apply_borders and apply_hypr_extras — writes the
# persistent Hyprland config file once all colors are known.
_write_hypr_colors_conf() {
    local col_active_1="$1"
    local col_active_2="$2"
    local col_inactive="$3"
    local shadow_col="$4"
    local shadow_inactive="$5"
    local group_active="$6"
    local group_inactive="$7"

    local hypr_colors_file="$HOME/.config/hypr/material-colors.conf"
    mkdir -p "$(dirname "$hypr_colors_file")"

    cat > "$hypr_colors_file" << HYPREOF
# Generated by applycolor.sh — do not edit manually.
# Sourced by hyprland.conf to persist colors across reboots.

general {
    col.active_border   = $col_active_1 $col_active_2 45deg
    col.inactive_border = $col_inactive
}

decoration {
    shadow {
        color         = $shadow_col
        color_inactive = $shadow_inactive
    }
}

group {
    col.border_active          = $group_active
    col.border_inactive        = $group_inactive
    col.border_locked_active   = $group_active
    col.border_locked_inactive = $group_inactive
}
HYPREOF
    echo "[applycolor] Hyprland colors written to $hypr_colors_file"
}

apply_borders() {
    if ! command -v hyprctl &>/dev/null; then
        echo "[applycolor] hyprctl not found — skipping border theming." >&2
        return 0
    fi

    local primary="" primary_container="" surface_variant="" scrim=""
    for i in "${!colorlist[@]}"; do
        case "${colorlist[$i]}" in
            '$primary')          primary="${colorvalues[$i]}"          ;;
            '$primaryContainer') primary_container="${colorvalues[$i]}" ;;
            '$surfaceVariant')   surface_variant="${colorvalues[$i]}"  ;;
            '$scrim')            scrim="${colorvalues[$i]}"            ;;
        esac
    done

    primary="${primary:-#8aadf4}"
    primary_container="${primary_container:-#6e8fd4}"
    surface_variant="${surface_variant:-#45475a}"
    scrim="${scrim:-#000000}"

    # Hyprland color format: 0xAARRGGBB
    local col_active_1="0xff${primary#\#}"
    local col_active_2="0xff${primary_container#\#}"
    local col_inactive="0xff${surface_variant#\#}"
    local shadow_col="0x88${primary#\#}"
    local shadow_inactive="0x44${scrim#\#}"
    local group_active="0xff${primary#\#}"
    local group_inactive="0xff${surface_variant#\#}"

    # Apply live (takes effect immediately)
    hyprctl keyword general:col.active_border        "$col_active_1 $col_active_2 45deg" 2>/dev/null
    hyprctl keyword general:col.inactive_border      "$col_inactive"                     2>/dev/null
    hyprctl keyword decoration:shadow:color         "$shadow_col"      2>/dev/null
    hyprctl keyword decoration:shadow:color_inactive "$shadow_inactive" 2>/dev/null
    hyprctl keyword group:col.border_active          "$group_active"                     2>/dev/null
    hyprctl keyword group:col.border_inactive        "$group_inactive"                   2>/dev/null
    hyprctl keyword group:col.border_locked_active   "$group_active"                     2>/dev/null
    hyprctl keyword group:col.border_locked_inactive "$group_inactive"                   2>/dev/null

    # Write persistent config so colors survive reboots
    _write_hypr_colors_conf         "$col_active_1" "$col_active_2" "$col_inactive"         "$shadow_col" "$shadow_inactive"         "$group_active" "$group_inactive"
}

# ---------------------------------------------------------------------------
# GTK4 colors.css — written to ~/.config/gtk-4.0/colors.css which GTK4
# loads automatically. Running apps pick it up on next theme refresh;
# most do so instantly. Maps Material You roles to GTK4 color variables.
# ---------------------------------------------------------------------------
apply_gtk4() {
    local gtk4_dir="$HOME/.config/gtk-4.0"
    mkdir -p "$gtk4_dir"

    # Pull the colors we need from the parsed arrays
    local primary="" on_primary="" primary_container="" on_primary_container=""
    local secondary="" on_secondary="" secondary_container="" on_secondary_container=""
    local surface="" on_surface="" surface_variant="" on_surface_variant=""
    local surface_container="" surface_container_high="" surface_container_low=""
    local error="" on_error="" error_container="" on_error_container=""
    local outline="" outline_variant="" inverse_surface="" inverse_on_surface=""

    for i in "${!colorlist[@]}"; do
        case "${colorlist[$i]}" in
            '$primary')                 primary="${colorvalues[$i]}"                 ;;
            '$onPrimary')               on_primary="${colorvalues[$i]}"              ;;
            '$primaryContainer')        primary_container="${colorvalues[$i]}"       ;;
            '$onPrimaryContainer')      on_primary_container="${colorvalues[$i]}"    ;;
            '$secondary')               secondary="${colorvalues[$i]}"               ;;
            '$onSecondary')             on_secondary="${colorvalues[$i]}"            ;;
            '$secondaryContainer')      secondary_container="${colorvalues[$i]}"     ;;
            '$onSecondaryContainer')    on_secondary_container="${colorvalues[$i]}"  ;;
            '$surface')                 surface="${colorvalues[$i]}"                 ;;
            '$onSurface')               on_surface="${colorvalues[$i]}"              ;;
            '$surfaceVariant')          surface_variant="${colorvalues[$i]}"         ;;
            '$onSurfaceVariant')        on_surface_variant="${colorvalues[$i]}"      ;;
            '$surfaceContainer')        surface_container="${colorvalues[$i]}"       ;;
            '$surfaceContainerHigh')    surface_container_high="${colorvalues[$i]}"  ;;
            '$surfaceContainerLow')     surface_container_low="${colorvalues[$i]}"   ;;
            '$error')                   error="${colorvalues[$i]}"                   ;;
            '$onError')                 on_error="${colorvalues[$i]}"                ;;
            '$errorContainer')          error_container="${colorvalues[$i]}"         ;;
            '$onErrorContainer')        on_error_container="${colorvalues[$i]}"      ;;
            '$outline')                 outline="${colorvalues[$i]}"                 ;;
            '$outlineVariant')          outline_variant="${colorvalues[$i]}"         ;;
            '$inverseSurface')          inverse_surface="${colorvalues[$i]}"         ;;
            '$inverseOnSurface')        inverse_on_surface="${colorvalues[$i]}"      ;;
        esac
    done

    # Write the CSS — GTK4 picks this up automatically
    cat > "$gtk4_dir/colors.css" << CSSEOF
@define-color accent_color ${primary};
@define-color accent_bg_color ${primary};
@define-color accent_fg_color ${on_primary};

@define-color destructive_color ${error};
@define-color destructive_bg_color ${error_container};
@define-color destructive_fg_color ${on_error_container};

@define-color success_color #4F6354;
@define-color success_bg_color #D1E8D5;
@define-color success_fg_color #0C1F13;

@define-color warning_color #E6B800;
@define-color warning_bg_color #FFF3CD;
@define-color warning_fg_color #664D00;

@define-color error_color ${error};
@define-color error_bg_color ${error_container};
@define-color error_fg_color ${on_error_container};

@define-color window_bg_color ${surface};
@define-color window_fg_color ${on_surface};

@define-color view_bg_color ${surface_container_low};
@define-color view_fg_color ${on_surface};

@define-color headerbar_bg_color ${surface_container};
@define-color headerbar_fg_color ${on_surface};
@define-color headerbar_border_color ${outline_variant};
@define-color headerbar_backdrop_color ${surface_container_low};
@define-color headerbar_shade_color ${outline_variant};

@define-color card_bg_color ${surface_container_high};
@define-color card_fg_color ${on_surface};
@define-color card_shade_color ${outline_variant};

@define-color dialog_bg_color ${surface_container};
@define-color dialog_fg_color ${on_surface};

@define-color popover_bg_color ${surface_container};
@define-color popover_fg_color ${on_surface};
@define-color popover_shade_color ${outline_variant};

@define-color shade_color ${outline_variant};
@define-color scrollbar_outline_color ${outline};

@define-color sidebar_bg_color ${surface_container_low};
@define-color sidebar_fg_color ${on_surface};
@define-color sidebar_backdrop_color ${surface};
@define-color sidebar_shade_color ${outline_variant};

@define-color secondary_sidebar_bg_color ${surface_container};
@define-color secondary_sidebar_fg_color ${on_surface_variant};
@define-color secondary_sidebar_backdrop_color ${surface_container_low};
@define-color secondary_sidebar_shade_color ${outline_variant};
CSSEOF

    echo "[applycolor] GTK4 colors written to $gtk4_dir/colors.css"
}

# ---------------------------------------------------------------------------
# Hyprland extra visuals — shadows, groups, dim
# All applied live via hyprctl keyword, no restart needed
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Kitty — writes a theme file and reloads all running instances live
# Kitty supports live reload via SIGUSR1
# ---------------------------------------------------------------------------
apply_kitty() {
    local kitty_theme_dir="$HOME/.config/kitty"
    local kitty_theme_file="$kitty_theme_dir/material-colors.conf"
    mkdir -p "$kitty_theme_dir"

    local background="" foreground="" cursor="" selection_bg="" selection_fg=""
    local black="" red="" green="" yellow="" blue="" magenta="" cyan="" white=""
    local br_black="" br_red="" br_green="" br_yellow=""
    local br_blue="" br_magenta="" br_cyan="" br_white=""

    for i in "${!colorlist[@]}"; do
        case "${colorlist[$i]}" in
            '$surface')              background="${colorvalues[$i]}"   ;;
            '$onSurface')            foreground="${colorvalues[$i]}"   ;;
            '$primary')              cursor="${colorvalues[$i]}"       ;;
            '$primaryContainer')     selection_bg="${colorvalues[$i]}" ;;
            '$onPrimaryContainer')   selection_fg="${colorvalues[$i]}" ;;
            '$term0')   black="${colorvalues[$i]}"     ;;
            '$term1')   red="${colorvalues[$i]}"       ;;
            '$term2')   green="${colorvalues[$i]}"     ;;
            '$term3')   yellow="${colorvalues[$i]}"    ;;
            '$term4')   blue="${colorvalues[$i]}"      ;;
            '$term5')   magenta="${colorvalues[$i]}"   ;;
            '$term6')   cyan="${colorvalues[$i]}"      ;;
            '$term7')   white="${colorvalues[$i]}"     ;;
            '$term8')   br_black="${colorvalues[$i]}"  ;;
            '$term9')   br_red="${colorvalues[$i]}"    ;;
            '$term10')  br_green="${colorvalues[$i]}"  ;;
            '$term11')  br_yellow="${colorvalues[$i]}" ;;
            '$term12')  br_blue="${colorvalues[$i]}"   ;;
            '$term13')  br_magenta="${colorvalues[$i]}";;
            '$term14')  br_cyan="${colorvalues[$i]}"   ;;
            '$term15')  br_white="${colorvalues[$i]}"  ;;
        esac
    done

    cat > "$kitty_theme_file" << KITTYEOF
# Generated by applycolor.sh — do not edit manually
background            ${background}
foreground            ${foreground}
cursor                ${cursor}
cursor_text_color     ${background}
selection_background  ${selection_bg}
selection_foreground  ${selection_fg}

color0  ${black}
color1  ${red}
color2  ${green}
color3  ${yellow}
color4  ${blue}
color5  ${magenta}
color6  ${cyan}
color7  ${white}
color8  ${br_black}
color9  ${br_red}
color10 ${br_green}
color11 ${br_yellow}
color12 ${br_blue}
color13 ${br_magenta}
color14 ${br_cyan}
color15 ${br_white}
KITTYEOF

    # Ensure kitty.conf includes our theme file (add once if missing)
    local kitty_conf="$kitty_theme_dir/kitty.conf"
    if [[ -f "$kitty_conf" ]] && ! grep -q "material-colors.conf" "$kitty_conf"; then
        echo "include material-colors.conf" >> "$kitty_conf"
    fi

    # Live-reload all running kitty instances
    pkill -SIGUSR1 kitty 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Rofi — writes a colors.rasi theme file; rofi reads it fresh each launch
# ---------------------------------------------------------------------------
apply_rofi() {
    local rofi_dir="$HOME/.config/rofi"
    mkdir -p "$rofi_dir"

    local background="" on_surface="" primary="" on_primary=""
    local surface_container="" surface_container_high="" outline_variant=""

    for i in "${!colorlist[@]}"; do
        case "${colorlist[$i]}" in
            '$surface')               background="${colorvalues[$i]}"           ;;
            '$onSurface')             on_surface="${colorvalues[$i]}"           ;;
            '$primary')               primary="${colorvalues[$i]}"              ;;
            '$onPrimary')             on_primary="${colorvalues[$i]}"           ;;
            '$surfaceContainer')      surface_container="${colorvalues[$i]}"    ;;
            '$surfaceContainerHigh')  surface_container_high="${colorvalues[$i]}" ;;
            '$outlineVariant')        outline_variant="${colorvalues[$i]}"      ;;
        esac
    done

    cat > "$rofi_dir/material-colors.rasi" << ROFIEOF
/* Generated by applycolor.sh — do not edit manually */
* {
    bg:          ${background};
    bg-alt:      ${surface_container};
    bg-selected: ${surface_container_high};
    fg:          ${on_surface};
    fg-selected: ${on_primary};
    accent:      ${primary};
    border:      ${outline_variant};
}
ROFIEOF

    # If a main rofi config exists, ensure it imports our colors
    local rofi_conf="$rofi_dir/config.rasi"
    if [[ -f "$rofi_conf" ]] && ! grep -q "material-colors.rasi" "$rofi_conf"; then
        # Prepend the import at the top
        sed -i '1s|^|@import "material-colors.rasi"\n|' "$rofi_conf"
    elif [[ ! -f "$rofi_conf" ]]; then
        echo '@import "material-colors.rasi"' > "$rofi_conf"
    fi
}

# ---------------------------------------------------------------------------
# VSCode — writes to user settings.json workbench.colorCustomizations
# Only touches the color keys; leaves all other settings intact
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# CONFIG_DIR is only needed for apply_qt, so warn but don't hard-exit
# ---------------------------------------------------------------------------
if [[ -d "$CONFIG_DIR" ]]; then
    cd "$CONFIG_DIR"
else
    echo "[applycolor] Warning: CONFIG_DIR '$CONFIG_DIR' does not exist." >&2
fi

# ---------------------------------------------------------------------------
# Always apply terminal theming — check config if it exists, otherwise
# default to enabled so colours are never silently skipped.
# ---------------------------------------------------------------------------
if [[ -f "$CONFIG_FILE" ]]; then
    enable_terminal=$(jq -r '.appearance.wallpaperTheming.enableTerminal' "$CONFIG_FILE")
    if [[ "$enable_terminal" == "true" ]]; then
        apply_term &
    else
        echo "[applycolor] Terminal theming disabled in config." >&2
    fi
else
    echo "[applycolor] Config not found at $CONFIG_FILE — applying terminal theming by default." >&2
    apply_term &
fi

apply_gtk4 &        # GTK4 colors.css — picked up automatically by running apps
apply_kitty &        # Kitty terminal config + live reload
apply_rofi &         # Rofi color theme file
# VSCode is handled by material-code-set-color.sh (called from switchwall.sh post_process)
apply_borders &  # Always apply — hyprctl is safe to call any time Hyprland is running
# apply_qt &  # Qt theming already handled by kde-material-colors

wait
